/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;


import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author sebastianqr.2208
 */
public class Proyecto2 extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    private int pantallaSeleccionada = 1;
  
    public Proyecto2() {
        initComponents();
        JPanelImage_Multicilclo imagenMulticiclo=new JPanelImage_Multicilclo(panel_multiciclo);
        panel_multiciclo.add(imagenMulticiclo).repaint();
        pantallas.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        pantallas = new javax.swing.JTabbedPane();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uniciclo_radio = new javax.swing.JRadioButton();
        multiciclo_radio = new javax.swing.JRadioButton();
        iniciarCambio = new javax.swing.JButton();
        uniciclo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        step_by_step_uniciclo = new javax.swing.JButton();
        complete_uniciclo = new javax.swing.JButton();
        con_ciclo_a_uniciclo = new javax.swing.JButton();
        segundos_field_uniciclo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        infor_ejecucion_uniciclo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        valores_registro_uniciclo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        valores_memoria_uniciclo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        multiciclo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        step_by_step_multiciclo = new javax.swing.JButton();
        complete_multiciclo = new javax.swing.JButton();
        con_ciclo_a_multiciclo = new javax.swing.JButton();
        segundos_field_multiciclo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        info_ejecucion_multiciclo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        valores_registro_multiciclo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        valores_memoria_multiciclo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_multiciclo = new javax.swing.JPanel();
        Boton_Imm_Multi = new javax.swing.JButton();
        Boton_Pc_Multi = new javax.swing.JButton();
        Boton_Memoria_Multi = new javax.swing.JButton();
        Boton_Decode_Multi = new javax.swing.JButton();
        Boton_Registro_Multi = new javax.swing.JButton();
        Boton_ALU_Multi = new javax.swing.JButton();
        Label_Pc4_Multi = new javax.swing.JLabel();
        Label_pctarget_Multi = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallas.setBackground(new java.awt.Color(255, 255, 255));
        pantallas.setPreferredSize(new java.awt.Dimension(1083, 698));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Escoja el procesador en el que desea ejecutar la Criba de Eratóstenes:");

        uniciclo_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        uniciclo_radio.setText("Uniciclo");
        uniciclo_radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                uniciclo_radioStateChanged(evt);
            }
        });
        uniciclo_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniciclo_radioActionPerformed(evt);
            }
        });

        multiciclo_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        multiciclo_radio.setText("Multiciclo");
        multiciclo_radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                multiciclo_radioStateChanged(evt);
            }
        });
        multiciclo_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiciclo_radioActionPerformed(evt);
            }
        });

        iniciarCambio.setBackground(new java.awt.Color(152, 165, 174));
        iniciarCambio.setText("Iniciar");
        iniciarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(iniciarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuLayout.createSequentialGroup()
                            .addGap(319, 319, 319)
                            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multiciclo_radio)
                                .addComponent(uniciclo_radio))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uniciclo_radio)
                .addGap(18, 18, 18)
                .addComponent(multiciclo_radio)
                .addGap(78, 78, 78)
                .addComponent(iniciarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pantallas.addTab("tab1", menu);

        uniciclo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel2.setText("Procesador Uniciclo");

        jLabel3.setText("Modos de Ejecución:");

        step_by_step_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        step_by_step_uniciclo.setText("Step by step");
        step_by_step_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step_by_step_unicicloActionPerformed(evt);
            }
        });

        complete_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        complete_uniciclo.setText("Complete");
        complete_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_unicicloActionPerformed(evt);
            }
        });

        con_ciclo_a_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        con_ciclo_a_uniciclo.setText("Con ciclo a:");
        con_ciclo_a_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_ciclo_a_unicicloActionPerformed(evt);
            }
        });

        segundos_field_uniciclo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("segundos");

        infor_ejecucion_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        infor_ejecucion_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel6.setText("Información de Ejecución");

        javax.swing.GroupLayout infor_ejecucion_unicicloLayout = new javax.swing.GroupLayout(infor_ejecucion_uniciclo);
        infor_ejecucion_uniciclo.setLayout(infor_ejecucion_unicicloLayout);
        infor_ejecucion_unicicloLayout.setHorizontalGroup(
            infor_ejecucion_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infor_ejecucion_unicicloLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        infor_ejecucion_unicicloLayout.setVerticalGroup(
            infor_ejecucion_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infor_ejecucion_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        valores_registro_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_registro_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel7.setText("Valores de Registro");

        javax.swing.GroupLayout valores_registro_unicicloLayout = new javax.swing.GroupLayout(valores_registro_uniciclo);
        valores_registro_uniciclo.setLayout(valores_registro_unicicloLayout);
        valores_registro_unicicloLayout.setHorizontalGroup(
            valores_registro_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_registro_unicicloLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(111, 111, 111))
        );
        valores_registro_unicicloLayout.setVerticalGroup(
            valores_registro_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_registro_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        valores_memoria_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_memoria_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel8.setText("Valores de Memoria");

        javax.swing.GroupLayout valores_memoria_unicicloLayout = new javax.swing.GroupLayout(valores_memoria_uniciclo);
        valores_memoria_uniciclo.setLayout(valores_memoria_unicicloLayout);
        valores_memoria_unicicloLayout.setHorizontalGroup(
            valores_memoria_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_memoria_unicicloLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(105, 105, 105))
        );
        valores_memoria_unicicloLayout.setVerticalGroup(
            valores_memoria_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_memoria_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout unicicloLayout = new javax.swing.GroupLayout(uniciclo);
        uniciclo.setLayout(unicicloLayout);
        unicicloLayout.setHorizontalGroup(
            unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unicicloLayout.createSequentialGroup()
                .addComponent(infor_ejecucion_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(valores_registro_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(valores_memoria_uniciclo, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
            .addGroup(unicicloLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(unicicloLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(step_by_step_uniciclo)
                        .addGap(43, 43, 43)
                        .addComponent(complete_uniciclo)
                        .addGap(36, 36, 36)
                        .addComponent(con_ciclo_a_uniciclo)
                        .addGap(6, 6, 6)
                        .addComponent(segundos_field_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))))
        );
        unicicloLayout.setVerticalGroup(
            unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unicicloLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(step_by_step_uniciclo)
                    .addComponent(complete_uniciclo)
                    .addComponent(con_ciclo_a_uniciclo)
                    .addComponent(segundos_field_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(unicicloLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(450, 450, 450)
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infor_ejecucion_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_registro_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_memoria_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pantallas.addTab("tab2", uniciclo);

        multiciclo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel9.setText("Procesador Multiciclo");

        jLabel10.setText("Modos de Ejecución:");

        step_by_step_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        step_by_step_multiciclo.setText("Step by step");
        step_by_step_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step_by_step_multicicloActionPerformed(evt);
            }
        });

        complete_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        complete_multiciclo.setText("Complete");
        complete_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_multicicloActionPerformed(evt);
            }
        });

        con_ciclo_a_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        con_ciclo_a_multiciclo.setText("Con ciclo a:");
        con_ciclo_a_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_ciclo_a_multicicloActionPerformed(evt);
            }
        });

        segundos_field_multiciclo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("segundos");

        info_ejecucion_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        info_ejecucion_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel12.setText("Información de Ejecución");

        javax.swing.GroupLayout info_ejecucion_multicicloLayout = new javax.swing.GroupLayout(info_ejecucion_multiciclo);
        info_ejecucion_multiciclo.setLayout(info_ejecucion_multicicloLayout);
        info_ejecucion_multicicloLayout.setHorizontalGroup(
            info_ejecucion_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_ejecucion_multicicloLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel12)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        info_ejecucion_multicicloLayout.setVerticalGroup(
            info_ejecucion_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_ejecucion_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        valores_registro_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_registro_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel13.setText("Valores de Registro");

        javax.swing.GroupLayout valores_registro_multicicloLayout = new javax.swing.GroupLayout(valores_registro_multiciclo);
        valores_registro_multiciclo.setLayout(valores_registro_multicicloLayout);
        valores_registro_multicicloLayout.setHorizontalGroup(
            valores_registro_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_registro_multicicloLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(111, 111, 111))
        );
        valores_registro_multicicloLayout.setVerticalGroup(
            valores_registro_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_registro_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        valores_memoria_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_memoria_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel14.setText("Valores de Memoria");

        javax.swing.GroupLayout valores_memoria_multicicloLayout = new javax.swing.GroupLayout(valores_memoria_multiciclo);
        valores_memoria_multiciclo.setLayout(valores_memoria_multicicloLayout);
        valores_memoria_multicicloLayout.setHorizontalGroup(
            valores_memoria_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_memoria_multicicloLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(105, 105, 105))
        );
        valores_memoria_multicicloLayout.setVerticalGroup(
            valores_memoria_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_memoria_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        Boton_Imm_Multi.setText("Imm");
        Boton_Imm_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Imm_MultiActionPerformed(evt);
            }
        });

        Boton_Pc_Multi.setText("PC");
        Boton_Pc_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Pc_MultiActionPerformed(evt);
            }
        });

        Boton_Memoria_Multi.setText("Memoria de Instrucciones y Datos");
        Boton_Memoria_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Memoria_MultiActionPerformed(evt);
            }
        });

        Boton_Decode_Multi.setText("Decode");
        Boton_Decode_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Decode_MultiActionPerformed(evt);
            }
        });

        Boton_Registro_Multi.setText("Registros");
        Boton_Registro_Multi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Registro_Multi.setBorderPainted(false);
        Boton_Registro_Multi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Boton_Registro_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Registro_MultiActionPerformed(evt);
            }
        });

        Boton_ALU_Multi.setText("ALU");
        Boton_ALU_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ALU_MultiActionPerformed(evt);
            }
        });

        Label_Pc4_Multi.setText("+4");

        Label_pctarget_Multi.setText("Pc Target");

        javax.swing.GroupLayout panel_multicicloLayout = new javax.swing.GroupLayout(panel_multiciclo);
        panel_multiciclo.setLayout(panel_multicicloLayout);
        panel_multicicloLayout.setHorizontalGroup(
            panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_multicicloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Pc4_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_pctarget_Multi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Pc_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Boton_Memoria_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Boton_Decode_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Imm_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addComponent(Boton_Registro_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(Boton_ALU_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(191, 191, 191))
        );
        panel_multicicloLayout.setVerticalGroup(
            panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_multicicloLayout.createSequentialGroup()
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_Memoria_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Decode_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Pc_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Registro_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_ALU_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(Boton_Imm_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Label_Pc4_Multi)
                        .addGap(32, 32, 32)
                        .addComponent(Label_pctarget_Multi)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout multicicloLayout = new javax.swing.GroupLayout(multiciclo);
        multiciclo.setLayout(multicicloLayout);
        multicicloLayout.setHorizontalGroup(
            multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multicicloLayout.createSequentialGroup()
                .addComponent(info_ejecucion_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_registro_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_memoria_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
            .addGroup(multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multicicloLayout.createSequentialGroup()
                        .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(multicicloLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(39, 39, 39)
                                .addComponent(step_by_step_multiciclo)
                                .addGap(43, 43, 43)
                                .addComponent(complete_multiciclo)
                                .addGap(36, 36, 36)
                                .addComponent(con_ciclo_a_multiciclo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(segundos_field_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        multicicloLayout.setVerticalGroup(
            multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(step_by_step_multiciclo)
                    .addComponent(complete_multiciclo)
                    .addComponent(con_ciclo_a_multiciclo)
                    .addComponent(segundos_field_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(panel_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_ejecucion_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_registro_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_memoria_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pantallas.addTab("tab3", multiciclo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void con_ciclo_a_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_ciclo_a_multicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_ciclo_a_multicicloActionPerformed

    private void complete_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_multicicloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_complete_multicicloActionPerformed

    private void step_by_step_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step_by_step_multicicloActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_step_by_step_multicicloActionPerformed

    private void con_ciclo_a_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_ciclo_a_unicicloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_con_ciclo_a_unicicloActionPerformed

    private void complete_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_unicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complete_unicicloActionPerformed

    private void step_by_step_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step_by_step_unicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_step_by_step_unicicloActionPerformed

    private void iniciarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCambioActionPerformed
        // TODO add your handling code here:
        if(uniciclo_radio.isSelected() || multiciclo_radio.isSelected()){
            pantallas.setSelectedIndex(pantallaSeleccionada);
        }
        else{
            JOptionPane.showMessageDialog(pantallas, "Debe seleccionar algún modo ", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_iniciarCambioActionPerformed

    private void multiciclo_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiciclo_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiciclo_radioActionPerformed

    private void multiciclo_radioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_multiciclo_radioStateChanged
        // TODO add your handling code here:
        if(multiciclo_radio.isSelected()){
            uniciclo_radio.setSelected(false);
            pantallaSeleccionada = 2;
        }
    }//GEN-LAST:event_multiciclo_radioStateChanged

    private void uniciclo_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniciclo_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniciclo_radioActionPerformed

    private void uniciclo_radioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_uniciclo_radioStateChanged
        // TODO add your handling code here:
        if(uniciclo_radio.isSelected()){
            multiciclo_radio.setSelected(false);
            pantallaSeleccionada = 1;
        }
    }//GEN-LAST:event_uniciclo_radioStateChanged

    private void Boton_Imm_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Imm_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Imm_MultiActionPerformed

    private void Boton_Pc_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Pc_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Pc_MultiActionPerformed

    private void Boton_Memoria_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Memoria_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Memoria_MultiActionPerformed

    private void Boton_Decode_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Decode_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Decode_MultiActionPerformed

    private void Boton_Registro_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Registro_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Registro_MultiActionPerformed

    private void Boton_ALU_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ALU_MultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_ALU_MultiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_ALU_Multi;
    private javax.swing.JButton Boton_Decode_Multi;
    private javax.swing.JButton Boton_Imm_Multi;
    private javax.swing.JButton Boton_Memoria_Multi;
    private javax.swing.JButton Boton_Pc_Multi;
    private javax.swing.JButton Boton_Registro_Multi;
    private javax.swing.JLabel Label_Pc4_Multi;
    private javax.swing.JLabel Label_pctarget_Multi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton complete_multiciclo;
    private javax.swing.JButton complete_uniciclo;
    private javax.swing.JButton con_ciclo_a_multiciclo;
    private javax.swing.JButton con_ciclo_a_uniciclo;
    private javax.swing.JPanel info_ejecucion_multiciclo;
    private javax.swing.JPanel infor_ejecucion_uniciclo;
    private javax.swing.JButton iniciarCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel multiciclo;
    private javax.swing.JRadioButton multiciclo_radio;
    private javax.swing.JPanel panel_multiciclo;
    private javax.swing.JTabbedPane pantallas;
    private javax.swing.JTextField segundos_field_multiciclo;
    private javax.swing.JTextField segundos_field_uniciclo;
    private javax.swing.JButton step_by_step_multiciclo;
    private javax.swing.JButton step_by_step_uniciclo;
    private javax.swing.JPanel uniciclo;
    private javax.swing.JRadioButton uniciclo_radio;
    private javax.swing.JPanel valores_memoria_multiciclo;
    private javax.swing.JPanel valores_memoria_uniciclo;
    private javax.swing.JPanel valores_registro_multiciclo;
    private javax.swing.JPanel valores_registro_uniciclo;
    // End of variables declaration//GEN-END:variables
}
