/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;


import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author sebastianqr.2208
 */
public class Proyecto2 extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    private int pantallaSeleccionada = 1;
    private LineasUniciclo lineas_uni;
    private LineasMulticiclo lineas_multi;
    private Instrucciones instrucciones;
    
    //Lineas para uniciclo

    
    public Proyecto2() {
        initComponents();
        pantallas.setSelectedIndex(0);
        lineas_uni = new LineasUniciclo(this.panel_uniciclo);
        lineas_multi =new LineasMulticiclo(this.panel_multiciclo);
        instrucciones = new Instrucciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        pantallas = new javax.swing.JTabbedPane();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uniciclo_radio = new javax.swing.JRadioButton();
        multiciclo_radio = new javax.swing.JRadioButton();
        iniciarCambio = new javax.swing.JButton();
        uniciclo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        step_by_step_uniciclo = new javax.swing.JButton();
        complete_uniciclo = new javax.swing.JButton();
        con_ciclo_a_uniciclo = new javax.swing.JButton();
        segundos_field_uniciclo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        infor_ejecucion_uniciclo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uniciclo_info = new javax.swing.JTextArea();
        valores_registro_uniciclo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        valores_reg_uni = new javax.swing.JTextArea();
        valores_memoria_uniciclo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        valores_memoria_uni = new javax.swing.JTextArea();
        panel_uniciclo = new javax.swing.JPanel();
        Boton_PC_Uni = new javax.swing.JButton();
        Boton_Decode_Uni = new javax.swing.JButton();
        Boton_Imem_Uni = new javax.swing.JButton();
        Boton_Registro_Uni = new javax.swing.JButton();
        Boton_Imm_Uni = new javax.swing.JButton();
        Boton_ALU_uni = new javax.swing.JButton();
        Boton_Dmem_Uni = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        multiciclo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        step_by_step_multiciclo = new javax.swing.JButton();
        complete_multiciclo = new javax.swing.JButton();
        con_ciclo_a_multiciclo = new javax.swing.JButton();
        segundos_field_multiciclo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        info_ejecucion_multiciclo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        multi_complete = new javax.swing.JTextArea();
        valores_registro_multiciclo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        valores_registro_uni = new javax.swing.JScrollPane();
        valores_reg_multi = new javax.swing.JTextArea();
        valores_memoria_multiciclo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        valores_memori = new javax.swing.JScrollPane();
        valores_memoria_multi = new javax.swing.JTextArea();
        panel_multiciclo = new javax.swing.JPanel();
        Boton_Memoria_Multi = new javax.swing.JButton();
        Boton_PC_Multi1 = new javax.swing.JButton();
        Boton_Imm_Multi1 = new javax.swing.JButton();
        Boton_Decode_Multi2 = new javax.swing.JButton();
        Boton_Registros_Multi2 = new javax.swing.JButton();
        Boton_ALU_Multi2 = new javax.swing.JButton();
        Label_Pc4_Multi = new javax.swing.JLabel();
        Label_Pc4_Multi1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallas.setBackground(new java.awt.Color(255, 255, 255));
        pantallas.setPreferredSize(new java.awt.Dimension(1083, 698));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Escoja el procesador en el que desea ejecutar la Criba de Eratóstenes:");

        uniciclo_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        uniciclo_radio.setText("Uniciclo");
        uniciclo_radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                uniciclo_radioStateChanged(evt);
            }
        });
        uniciclo_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniciclo_radioActionPerformed(evt);
            }
        });

        multiciclo_radio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        multiciclo_radio.setText("Multiciclo");
        multiciclo_radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                multiciclo_radioStateChanged(evt);
            }
        });
        multiciclo_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiciclo_radioActionPerformed(evt);
            }
        });

        iniciarCambio.setBackground(new java.awt.Color(152, 165, 174));
        iniciarCambio.setText("Iniciar");
        iniciarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(iniciarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuLayout.createSequentialGroup()
                            .addGap(319, 319, 319)
                            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multiciclo_radio)
                                .addComponent(uniciclo_radio))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uniciclo_radio)
                .addGap(18, 18, 18)
                .addComponent(multiciclo_radio)
                .addGap(78, 78, 78)
                .addComponent(iniciarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pantallas.addTab("tab1", menu);

        uniciclo.setBackground(new java.awt.Color(255, 255, 255));
        uniciclo.setMinimumSize(new java.awt.Dimension(1083, 695));
        uniciclo.setPreferredSize(new java.awt.Dimension(1083, 695));

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel2.setText("Procesador Uniciclo");

        jLabel3.setText("Modos de Ejecución:");

        step_by_step_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        step_by_step_uniciclo.setText("Step by step");
        step_by_step_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step_by_step_unicicloActionPerformed(evt);
            }
        });

        complete_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        complete_uniciclo.setText("Complete");
        complete_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_unicicloActionPerformed(evt);
            }
        });

        con_ciclo_a_uniciclo.setBackground(new java.awt.Color(152, 165, 174));
        con_ciclo_a_uniciclo.setText("Con ciclo a:");
        con_ciclo_a_uniciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_ciclo_a_unicicloActionPerformed(evt);
            }
        });

        segundos_field_uniciclo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("segundos");

        infor_ejecucion_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        infor_ejecucion_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel6.setText("Información de Ejecución");

        uniciclo_info.setColumns(20);
        uniciclo_info.setRows(5);
        jScrollPane1.setViewportView(uniciclo_info);

        javax.swing.GroupLayout infor_ejecucion_unicicloLayout = new javax.swing.GroupLayout(infor_ejecucion_uniciclo);
        infor_ejecucion_uniciclo.setLayout(infor_ejecucion_unicicloLayout);
        infor_ejecucion_unicicloLayout.setHorizontalGroup(
            infor_ejecucion_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infor_ejecucion_unicicloLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(infor_ejecucion_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        infor_ejecucion_unicicloLayout.setVerticalGroup(
            infor_ejecucion_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infor_ejecucion_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        valores_registro_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_registro_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel7.setText("Valores de Registro");

        valores_reg_uni.setColumns(20);
        valores_reg_uni.setRows(5);
        jScrollPane4.setViewportView(valores_reg_uni);

        javax.swing.GroupLayout valores_registro_unicicloLayout = new javax.swing.GroupLayout(valores_registro_uniciclo);
        valores_registro_uniciclo.setLayout(valores_registro_unicicloLayout);
        valores_registro_unicicloLayout.setHorizontalGroup(
            valores_registro_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_registro_unicicloLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(111, 111, 111))
            .addGroup(valores_registro_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        valores_registro_unicicloLayout.setVerticalGroup(
            valores_registro_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_registro_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        valores_memoria_uniciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_memoria_uniciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel8.setText("Valores de Memoria");

        valores_memoria_uni.setColumns(20);
        valores_memoria_uni.setRows(5);
        jScrollPane3.setViewportView(valores_memoria_uni);

        javax.swing.GroupLayout valores_memoria_unicicloLayout = new javax.swing.GroupLayout(valores_memoria_uniciclo);
        valores_memoria_uniciclo.setLayout(valores_memoria_unicicloLayout);
        valores_memoria_unicicloLayout.setHorizontalGroup(
            valores_memoria_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_memoria_unicicloLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(105, 105, 105))
            .addGroup(valores_memoria_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        valores_memoria_unicicloLayout.setVerticalGroup(
            valores_memoria_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_memoria_unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_uniciclo.setBackground(new java.awt.Color(255, 255, 255));

        Boton_PC_Uni.setText("PC");
        Boton_PC_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PC_UniActionPerformed(evt);
            }
        });

        Boton_Decode_Uni.setText("Decodificador");
        Boton_Decode_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Decode_UniActionPerformed(evt);
            }
        });

        Boton_Imem_Uni.setText("Memoria de instrucciones");
        Boton_Imem_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Imem_UniActionPerformed(evt);
            }
        });

        Boton_Registro_Uni.setText("Registros");
        Boton_Registro_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Registro_UniActionPerformed(evt);
            }
        });

        Boton_Imm_Uni.setText("Imm");
        Boton_Imm_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Imm_UniActionPerformed(evt);
            }
        });

        Boton_ALU_uni.setText("ALU");
        Boton_ALU_uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ALU_uniActionPerformed(evt);
            }
        });

        Boton_Dmem_Uni.setText("Memoria de datos");
        Boton_Dmem_Uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Dmem_UniActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("+4");

        jLabel16.setText("PC Target");

        javax.swing.GroupLayout panel_unicicloLayout = new javax.swing.GroupLayout(panel_uniciclo);
        panel_uniciclo.setLayout(panel_unicicloLayout);
        panel_unicicloLayout.setHorizontalGroup(
            panel_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_unicicloLayout.createSequentialGroup()
                .addGap(539, 539, 539)
                .addComponent(Boton_Imm_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(439, 448, Short.MAX_VALUE))
            .addGroup(panel_unicicloLayout.createSequentialGroup()
                .addGroup(panel_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_unicicloLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addGap(46, 46, 46)
                .addComponent(Boton_PC_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Boton_Imem_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Boton_Decode_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(Boton_Registro_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(Boton_ALU_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(Boton_Dmem_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_unicicloLayout.setVerticalGroup(
            panel_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_unicicloLayout.createSequentialGroup()
                .addGroup(panel_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_unicicloLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(panel_unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_PC_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Imem_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Decode_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Registro_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_ALU_uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Dmem_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_unicicloLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)))
                .addGap(34, 34, 34)
                .addComponent(Boton_Imm_Uni, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout unicicloLayout = new javax.swing.GroupLayout(uniciclo);
        uniciclo.setLayout(unicicloLayout);
        unicicloLayout.setHorizontalGroup(
            unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(unicicloLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(step_by_step_uniciclo)
                        .addGap(43, 43, 43)
                        .addComponent(complete_uniciclo)
                        .addGap(36, 36, 36)
                        .addComponent(con_ciclo_a_uniciclo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundos_field_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(unicicloLayout.createSequentialGroup()
                .addComponent(infor_ejecucion_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_registro_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_memoria_uniciclo, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
            .addComponent(panel_uniciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        unicicloLayout.setVerticalGroup(
            unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(step_by_step_uniciclo)
                    .addComponent(complete_uniciclo)
                    .addComponent(con_ciclo_a_uniciclo)
                    .addComponent(segundos_field_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_uniciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(unicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infor_ejecucion_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_registro_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_memoria_uniciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pantallas.addTab("tab2", uniciclo);

        multiciclo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel9.setText("Procesador Multiciclo");

        jLabel10.setText("Modos de Ejecución:");

        step_by_step_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        step_by_step_multiciclo.setText("Step by step");
        step_by_step_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step_by_step_multicicloActionPerformed(evt);
            }
        });

        complete_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        complete_multiciclo.setText("Complete");
        complete_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_multicicloActionPerformed(evt);
            }
        });

        con_ciclo_a_multiciclo.setBackground(new java.awt.Color(152, 165, 174));
        con_ciclo_a_multiciclo.setText("Con ciclo a:");
        con_ciclo_a_multiciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_ciclo_a_multicicloActionPerformed(evt);
            }
        });

        segundos_field_multiciclo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("segundos");

        info_ejecucion_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        info_ejecucion_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel12.setText("Información de Ejecución");

        multi_complete.setColumns(20);
        multi_complete.setRows(5);
        jScrollPane2.setViewportView(multi_complete);

        javax.swing.GroupLayout info_ejecucion_multicicloLayout = new javax.swing.GroupLayout(info_ejecucion_multiciclo);
        info_ejecucion_multiciclo.setLayout(info_ejecucion_multicicloLayout);
        info_ejecucion_multicicloLayout.setHorizontalGroup(
            info_ejecucion_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_ejecucion_multicicloLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel12)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(info_ejecucion_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        info_ejecucion_multicicloLayout.setVerticalGroup(
            info_ejecucion_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_ejecucion_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        valores_registro_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_registro_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel13.setText("Valores de Registro");

        valores_reg_multi.setColumns(20);
        valores_reg_multi.setRows(5);
        valores_registro_uni.setViewportView(valores_reg_multi);

        javax.swing.GroupLayout valores_registro_multicicloLayout = new javax.swing.GroupLayout(valores_registro_multiciclo);
        valores_registro_multiciclo.setLayout(valores_registro_multicicloLayout);
        valores_registro_multicicloLayout.setHorizontalGroup(
            valores_registro_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_registro_multicicloLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(111, 111, 111))
            .addGroup(valores_registro_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valores_registro_uni)
                .addContainerGap())
        );
        valores_registro_multicicloLayout.setVerticalGroup(
            valores_registro_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_registro_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_registro_uni, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        valores_memoria_multiciclo.setBackground(new java.awt.Color(204, 204, 204));
        valores_memoria_multiciclo.setPreferredSize(new java.awt.Dimension(361, 180));

        jLabel14.setText("Valores de Memoria");

        valores_memoria_multi.setColumns(20);
        valores_memoria_multi.setRows(5);
        valores_memori.setViewportView(valores_memoria_multi);

        javax.swing.GroupLayout valores_memoria_multicicloLayout = new javax.swing.GroupLayout(valores_memoria_multiciclo);
        valores_memoria_multiciclo.setLayout(valores_memoria_multicicloLayout);
        valores_memoria_multicicloLayout.setHorizontalGroup(
            valores_memoria_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valores_memoria_multicicloLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(105, 105, 105))
            .addGroup(valores_memoria_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valores_memori)
                .addContainerGap())
        );
        valores_memoria_multicicloLayout.setVerticalGroup(
            valores_memoria_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valores_memoria_multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_memori, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        Boton_Memoria_Multi.setText("Memoria");

        Boton_PC_Multi1.setText("PC");

        Boton_Imm_Multi1.setText("Imm");
        Boton_Imm_Multi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Imm_Multi1ActionPerformed(evt);
            }
        });

        Boton_Decode_Multi2.setText("Decode");

        Boton_Registros_Multi2.setText("Registros");

        Boton_ALU_Multi2.setText("ALU");

        Label_Pc4_Multi.setText("+4");

        Label_Pc4_Multi1.setText("PC Target");

        javax.swing.GroupLayout panel_multicicloLayout = new javax.swing.GroupLayout(panel_multiciclo);
        panel_multiciclo.setLayout(panel_multicicloLayout);
        panel_multicicloLayout.setHorizontalGroup(
            panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_multicicloLayout.createSequentialGroup()
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Label_Pc4_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Label_Pc4_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Boton_PC_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Boton_Memoria_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Boton_Decode_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Imm_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_multicicloLayout.createSequentialGroup()
                        .addComponent(Boton_Registros_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(Boton_ALU_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        panel_multicicloLayout.setVerticalGroup(
            panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_multicicloLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Boton_Registros_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Decode_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Memoria_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_PC_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Boton_ALU_Multi2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(Boton_Imm_Multi1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(panel_multicicloLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Label_Pc4_Multi)
                .addGap(33, 33, 33)
                .addComponent(Label_Pc4_Multi1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout multicicloLayout = new javax.swing.GroupLayout(multiciclo);
        multiciclo.setLayout(multicicloLayout);
        multicicloLayout.setHorizontalGroup(
            multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multicicloLayout.createSequentialGroup()
                .addComponent(info_ejecucion_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_registro_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valores_memoria_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
            .addGroup(multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(multicicloLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(step_by_step_multiciclo)
                        .addGap(43, 43, 43)
                        .addComponent(complete_multiciclo)
                        .addGap(36, 36, 36)
                        .addComponent(con_ciclo_a_multiciclo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundos_field_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(multicicloLayout.createSequentialGroup()
                .addComponent(panel_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        multicicloLayout.setVerticalGroup(
            multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multicicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(step_by_step_multiciclo)
                    .addComponent(complete_multiciclo)
                    .addComponent(con_ciclo_a_multiciclo)
                    .addComponent(segundos_field_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_multiciclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(multicicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_ejecucion_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_registro_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valores_memoria_multiciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pantallas.addTab("tab3", multiciclo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void con_ciclo_a_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_ciclo_a_multicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_ciclo_a_multicicloActionPerformed

    private void complete_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_multicicloActionPerformed
        // TODO add your handling code here:
        multi_complete.setText("");
        instrucciones.pintarMulticicloComplete(multi_complete, lineas_multi, valores_memoria_multi, valores_reg_multi);
    }//GEN-LAST:event_complete_multicicloActionPerformed

    private void step_by_step_multicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step_by_step_multicicloActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_step_by_step_multicicloActionPerformed

    private void con_ciclo_a_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_ciclo_a_unicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_ciclo_a_unicicloActionPerformed

    private void complete_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_unicicloActionPerformed
        // TODO add your handling code here:
        uniciclo_info.setText("");
        instrucciones.pintarUnicicloComplete(uniciclo_info, lineas_uni, valores_memoria_uni, valores_reg_uni);
    }//GEN-LAST:event_complete_unicicloActionPerformed

    private void step_by_step_unicicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step_by_step_unicicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_step_by_step_unicicloActionPerformed

    private void iniciarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCambioActionPerformed
        // TODO add your handling code here:
        if(uniciclo_radio.isSelected() || multiciclo_radio.isSelected()){
            pantallas.setSelectedIndex(pantallaSeleccionada);
        }
        else{
            JOptionPane.showMessageDialog(pantallas, "Debe seleccionar algún modo ", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_iniciarCambioActionPerformed

    private void multiciclo_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiciclo_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiciclo_radioActionPerformed

    private void multiciclo_radioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_multiciclo_radioStateChanged
        // TODO add your handling code here:
        if(multiciclo_radio.isSelected()){
            uniciclo_radio.setSelected(false);
            pantallaSeleccionada = 2;
        }
    }//GEN-LAST:event_multiciclo_radioStateChanged

    private void uniciclo_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniciclo_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniciclo_radioActionPerformed

    private void uniciclo_radioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_uniciclo_radioStateChanged
        // TODO add your handling code here:
        if(uniciclo_radio.isSelected()){
            multiciclo_radio.setSelected(false);
            pantallaSeleccionada = 1;
        }
    }//GEN-LAST:event_uniciclo_radioStateChanged

    private void Boton_PC_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PC_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_PC_UniActionPerformed

    private void Boton_Decode_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Decode_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Decode_UniActionPerformed

    private void Boton_Imem_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Imem_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Imem_UniActionPerformed

    private void Boton_Registro_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Registro_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Registro_UniActionPerformed

    private void Boton_Imm_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Imm_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Imm_UniActionPerformed

    private void Boton_ALU_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ALU_uniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_ALU_uniActionPerformed

    private void Boton_Dmem_UniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Dmem_UniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Dmem_UniActionPerformed

    private void Boton_Imm_Multi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Imm_Multi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Imm_Multi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_ALU_Multi2;
    private javax.swing.JButton Boton_ALU_uni;
    private javax.swing.JButton Boton_Decode_Multi2;
    private javax.swing.JButton Boton_Decode_Uni;
    private javax.swing.JButton Boton_Dmem_Uni;
    private javax.swing.JButton Boton_Imem_Uni;
    private javax.swing.JButton Boton_Imm_Multi1;
    private javax.swing.JButton Boton_Imm_Uni;
    private javax.swing.JButton Boton_Memoria_Multi;
    private javax.swing.JButton Boton_PC_Multi1;
    private javax.swing.JButton Boton_PC_Uni;
    private javax.swing.JButton Boton_Registro_Uni;
    private javax.swing.JButton Boton_Registros_Multi2;
    private javax.swing.JLabel Label_Pc4_Multi;
    private javax.swing.JLabel Label_Pc4_Multi1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton complete_multiciclo;
    private javax.swing.JButton complete_uniciclo;
    private javax.swing.JButton con_ciclo_a_multiciclo;
    private javax.swing.JButton con_ciclo_a_uniciclo;
    private javax.swing.JPanel info_ejecucion_multiciclo;
    private javax.swing.JPanel infor_ejecucion_uniciclo;
    private javax.swing.JButton iniciarCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel menu;
    private javax.swing.JTextArea multi_complete;
    private javax.swing.JPanel multiciclo;
    private javax.swing.JRadioButton multiciclo_radio;
    private javax.swing.JPanel panel_multiciclo;
    private javax.swing.JPanel panel_uniciclo;
    private javax.swing.JTabbedPane pantallas;
    private javax.swing.JTextField segundos_field_multiciclo;
    private javax.swing.JTextField segundos_field_uniciclo;
    private javax.swing.JButton step_by_step_multiciclo;
    private javax.swing.JButton step_by_step_uniciclo;
    private javax.swing.JPanel uniciclo;
    private javax.swing.JTextArea uniciclo_info;
    private javax.swing.JRadioButton uniciclo_radio;
    private javax.swing.JScrollPane valores_memori;
    private javax.swing.JTextArea valores_memoria_multi;
    private javax.swing.JPanel valores_memoria_multiciclo;
    private javax.swing.JTextArea valores_memoria_uni;
    private javax.swing.JPanel valores_memoria_uniciclo;
    private javax.swing.JTextArea valores_reg_multi;
    private javax.swing.JTextArea valores_reg_uni;
    private javax.swing.JPanel valores_registro_multiciclo;
    private javax.swing.JScrollPane valores_registro_uni;
    private javax.swing.JPanel valores_registro_uniciclo;
    // End of variables declaration//GEN-END:variables
}
